(()=>{
const css=`.sf-help-btn{position:fixed;right:22px;bottom:22px;z-index:9998;border:0;border-radius:999px;padding:14px 18px;background:linear-gradient(135deg,#7c3aed,#8d2df0);color:#fff;font:800 14px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;box-shadow:0 12px 30px rgba(73,44,145,.28);cursor:pointer}.sf-help-panel{position:fixed;right:22px;bottom:82px;z-index:9999;width:min(410px,calc(100vw - 28px));max-height:min(650px,calc(100vh - 110px));display:none;flex-direction:column;background:#fff;border:1px solid rgba(40,49,84,.10);border-radius:24px;box-shadow:0 24px 70px rgba(35,30,78,.22);overflow:hidden;font:14px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;color:#121a31}.sf-help-panel.open{display:flex}.sf-help-head{padding:16px 18px;background:linear-gradient(135deg,#f3edff,#fff3e9);border-bottom:1px solid rgba(40,49,84,.08)}.sf-help-title{font-weight:850;font-size:17px}.sf-help-sub{margin-top:3px;color:#687289;font-size:12px}.sf-help-chat{padding:14px;display:flex;flex-direction:column;gap:10px;overflow:auto;min-height:270px}.sf-msg{max-width:91%;padding:10px 12px;border-radius:15px}.sf-bot{align-self:flex-start;background:#f3f0ff}.sf-user{align-self:flex-end;background:#7c3aed;color:#fff}.sf-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.sf-actions button,.sf-actions a{border:0;border-radius:10px;padding:8px 10px;font:800 12px/1.2 inherit;text-decoration:none;cursor:pointer}.sf-primary{background:#7c3aed;color:#fff}.sf-secondary{background:#fff;color:#6234c3;border:1px solid #ddd1f6!important}.sf-help-form{display:flex;gap:8px;padding:12px;border-top:1px solid #eee;background:#fbfbfd}.sf-help-form input{flex:1;min-width:0;border:1px solid #dfe2ea;border-radius:13px;padding:11px 12px;font:inherit;outline:none}.sf-help-form button{border:0;border-radius:13px;padding:0 14px;background:#7c3aed;color:#fff;font-weight:850}.sf-close{float:right;border:0;background:transparent;font-size:19px;cursor:pointer;color:#6c7382}.sf-tag{display:inline-block;margin-bottom:6px;font-size:10px;font-weight:850;text-transform:uppercase;letter-spacing:.4px;color:#6b3bd0}.sf-note{margin-top:7px;font-size:12px;color:#667085}@media(max-width:520px){.sf-help-btn{right:14px;bottom:14px}.sf-help-panel{right:14px;bottom:72px}.sf-help-form{display:grid}.sf-help-form button{padding:11px}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const btn=document.createElement('button');btn.className='sf-help-btn';btn.textContent='Помощник';
const panel=document.createElement('section');panel.className='sf-help-panel';panel.innerHTML='<div class="sf-help-head"><button class="sf-close" aria-label="Закрыть">×</button><div class="sf-help-title">Step & Flow · Помощник</div><div class="sf-help-sub">Веду по одному безопасному шагу</div></div><div class="sf-help-chat"><div class="sf-msg sf-bot">Опишите проблему обычными словами. Можно написать код ошибки — например <b>0x80070005</b>, «синий экран», «нет интернета» или «флешку не видит».</div></div><form class="sf-help-form"><input autocomplete="off" placeholder="Что случилось?"><button>Отправить</button></form>';
document.body.append(btn,panel);
const chat=panel.querySelector('.sf-help-chat'),form=panel.querySelector('form'),input=form.querySelector('input');
let router=null,flows=null,kb=null,errors=[];let session={flow:null,node:null};
const errFiles=['data/error-code-index-01.json','data/error-code-index-02.json','data/error-code-index-03.json'];
Promise.all([fetch('data/knowledge-router.json').then(r=>r.json()),fetch('data/diagnostic-flows.json').then(r=>r.json()),fetch('data/knowledge.json').then(r=>r.json()),...errFiles.map(f=>fetch(f).then(r=>r.json()).catch(()=>null))]).then(a=>{router=a[0];flows=a[1];kb=a[2];errors=a.slice(3).filter(Boolean)}).catch(()=>msg('Не удалось загрузить библиотеку. Обновите страницу.'));
const norm=v=>String(v||'').toLowerCase().replace(/ё/g,'е').replace(/[–—]/g,'-').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function msg(html,user=false){const d=document.createElement('div');d.className='sf-msg '+(user?'sf-user':'sf-bot');d.innerHTML=html;chat.appendChild(d);chat.scrollTop=chat.scrollHeight;return d}
function safety(q){return /(дым|запах.{0,8}гар|искр|залил|жидкост|диск.{0,12}(щелк|стуч))/i.test(q)}
function exactCode(q){const m=q.match(/0x[0-9a-f]{6,8}/i);return m&&m[0].toUpperCase()}
function deepFind(obj,pred){if(!obj||typeof obj!=='object')return null;if(pred(obj))return obj;for(const v of Object.values(obj)){const r=deepFind(v,pred);if(r)return r}return null}
function findError(code){for(const db of errors){const r=deepFind(db,o=>Object.values(o).some(v=>typeof v==='string'&&norm(v)===norm(code)));if(r)return r}return null}
function explicitIntent(q){const n=norm(q);const rules=[
['bsod',/(син(ий|его) экран|bsod|stop code|bugcheck)/],
['slow_pc',/(комп(ьютер)?\s+.*(медлен|тормоз|завис|долго дума)|медленно\s+работ|тормозит|тормозить|лагает|подвисает|очень медленн|долго загружа)/],
['internet',/(нет интернета|интернет.*не работ|wi[ -]?fi.*не работ|вай ?фай.*не работ|нет сети|сайты.*не открыва|соединение.*пропал)/],
['windows_boot',/(windows.*не загружа|не грузится windows|зациклил.*загруз|черн(ый|ого) экран.*включ)/],
['audio',/(нет звука|звук.*пропал|ничего не слыш|звук.*хрип|звук.*тих|наушник.*не слыш)/],
['camera',/(камера.*не работ|веб.?камера.*не работ|не видит камер|черн(ый|ого) экран.*камер)/],
['microphone',/(микрофон.*не работ|меня не слыш|микрофон.*тих|нет микрофон)/],
['printer',/(принтер.*не печат|не видит принтер|принтер.*офлайн|printer.*offline)/],
['usb',/(usb.*не работ|флешк.*не вид|usb.*не распоз)/],
['windows_update',/(windows update.*ошиб|обновлен.*не устанавли|не обновляется windows|ошибка обновлен)/],
['app_problem',/(программ.*не запуска|приложен.*не открыва|программ.*вылета|не устанавливается программ|не могу удалить программ)/]
];for(const [intent,re] of rules)if(re.test(n))return intent;return null}
function routeSymptom(q){const forced=explicitIntent(q);if(forced){const r=(router?.symptom_routes||[]).find(x=>x.intent===forced);return r||{intent:forced,target:forced==='slow_pc'?'diagnostic-flows:computer-slow':''}}const n=norm(q);let best=null,score=0;for(const r of (router?.symptom_routes||[])){for(const p of r.phrases||[]){const pn=norm(p);let s=0;if(n.includes(pn))s=100+pn.length;else for(const w of pn.split(/\s+/))if(w.length>3&&n.includes(w))s+=w.length;if(s>score){score=s;best=r}}}return score>=8?best:null}
function getFlow(id){return (flows?.flows||[]).find(f=>f.id===id)}
function startFlow(id){const f=getFlow(id);if(!f)return false;session={flow:f,node:f.start};renderNode();return true}
function gotoNode(id){if(!session.flow)return;if(id==='resolved'){msg('<span class="sf-tag">Готово</span><br><b>Проблема решена.</b><div class="sf-note">Если всё работает, больше ничего менять не нужно.</div>');session={flow:null,node:null};return}session.node=String(id||'').replace(/^goto:/,'');renderNode()}
function renderNode(){const n=session.flow?.nodes?.[session.node];if(!n){msg('Мне нужен результат предыдущего шага. Опишите, что вы видите на экране.');return}if(n.type==='router'){msg('<span class="sf-tag">'+esc(session.flow.title)+'</span><br>Напишите, что показал предыдущий шаг. Я выберу следующую ветку.');return}if(n.type==='end'||n.type==='escalate'){msg('<span class="sf-tag">'+esc(session.flow.title)+'</span><br>'+esc(n.text||'Следующий этап требует более глубокой диагностики.'));if(n.type==='end')session={flow:null,node:null};return}let h='<span class="sf-tag">'+esc(session.flow.title)+'</span><br>'+esc(n.text||'');if(n.help)h+='<div class="sf-note">'+esc(n.help)+'</div>';const box=msg(h);if(n.answers){const a=document.createElement('div');a.className='sf-actions';for(const [label,target] of Object.entries(n.answers)){const b=document.createElement('button');b.type='button';b.className=(label==='Да'||label==='Получилось'||label==='Нет')?'sf-primary':'sf-secondary';b.textContent=label;b.onclick=()=>{msg(esc(label),true);gotoNode(target)};a.appendChild(b)}box.appendChild(a)}else if(n.next&&n.type!=='handoff'){const a=document.createElement('div');a.className='sf-actions';const b=document.createElement('button');b.type='button';b.className='sf-primary';b.textContent='Сделал';b.onclick=()=>{msg('Сделал',true);gotoNode(n.next)};const u=document.createElement('button');u.type='button';u.className='sf-secondary';u.textContent='Не понимаю';u.onclick=()=>msg('Напишите, на каком месте вы остановились или что сейчас видите на экране.');a.append(b,u);box.appendChild(a)}else if(n.type==='handoff')msg('<div class="sf-note">Теперь просто напишите результат сюда.</div>')}
function handleActiveSession(q){const n=session.flow?.nodes?.[session.node];if(!n)return false;const x=norm(q);if(n.type==='router'){for(const rule of n.rules||[]){if((rule.contains||[]).some(t=>x.includes(norm(t)))){gotoNode(rule.goto);return true}}gotoNode(n.fallback||'');return true}if(n.type==='handoff'){msg('Принял результат. Продолжаем по этой же ветке.');gotoNode(n.next);return true}if(n.answers){let key=null;if(/^(да|ага|yes|получилось|нашел|нашёл|открылось)$/i.test(x))key=Object.keys(n.answers).find(k=>/да|получилось|нашел|нашёл|открылось/i.test(k));else if(/^(нет|no|не получилось|не вижу)$/i.test(x))key=Object.keys(n.answers).find(k=>/нет|не получилось/i.test(k));else if(/не знаю|не понимаю|не уверен/.test(x))key=Object.keys(n.answers).find(k=>/не знаю|не понимаю/i.test(k));if(key){gotoNode(n.answers[key]);return true}}return false}
function simpleKb(q){q=norm(q);let best=null,score=0;for(const t of (kb?.topics||[])){let s=0;for(const k0 of [t.title,...(t.keywords||[])]){const k=norm(k0);if(q.includes(k)||k.includes(q))s+=k.length+20;else for(const w of k.split(/\s+/))if(w.length>3&&q.includes(w))s+=w.length}if(s>score){score=s;best=t}}return score>=5?best:null}
function respond(q){if(safety(q)){msg('<b>Остановимся на безопасном этапе.</b><br>Выключите компьютер и отключите питание, если это можно сделать безопасно. При запахе гари, дыме, искрах, жидкости или механических щелчках диска не запускайте ремонтные команды.');session={flow:null,node:null};return}if(handleActiveSession(q))return;const code=exactCode(q);if(code){const hit=findError(code);if(hit){const text=hit.user_message||hit.summary||hit.description||hit.meaning||hit.title||'Код найден в базе.';msg('<span class="sf-tag">Код '+esc(code)+'</span><br><b>Код найден.</b><br>'+esc(text)+'<div class="sf-note">Напишите, где он появился: обновление Windows, синий экран, установка программы или другое.</div>');return}}
const r=routeSymptom(q);if(r){const target=String(r.target||'');if(target.startsWith('diagnostic-flows:')&&startFlow(target.split(':')[1]))return;if(r.intent==='slow_pc'&&startFlow('computer-slow'))return;if(r.intent==='windows_boot'&&startFlow('unexpected-restart'))return;if(r.intent==='windows_update'){msg('<b>Понял: проблема с Windows Update.</b><br>Если на экране есть код вида <b>0x...</b>, отправьте его сюда. Если кода нет — напишите «кода нет».');return}if(['audio','camera','microphone'].includes(r.intent)){msg('<b>Сначала одно уточнение.</b><br>Это не работает во всех программах или только в одной?');return}msg('<b>Я нашёл подходящее направление.</b><br>Опишите одним предложением, что именно сейчас видно на экране.');return}
const t=simpleKb(q);if(t){msg('<b>'+esc(t.title)+'</b><br>Первый безопасный шаг:<br>'+esc(t.first_step)+(t.page?'<div class="sf-actions"><a class="sf-secondary" href="'+encodeURI(t.page)+'">Открыть инструкцию →</a></div>':''));return}msg('<b>Нужно одно уточнение.</b><br>Что именно не работает: Windows, интернет, звук, программа, USB/флешка, принтер, камера или что-то другое?')}
btn.onclick=()=>{panel.classList.toggle('open');if(panel.classList.contains('open'))setTimeout(()=>input.focus(),50)};panel.querySelector('.sf-close').onclick=()=>panel.classList.remove('open');form.onsubmit=e=>{e.preventDefault();const q=input.value.trim();if(!q)return;msg(esc(q),true);input.value='';if(!router||!flows){msg('Библиотека ещё загружается. Попробуйте через секунду.');return}respond(q)};
})();