(()=>{
const ENDPOINT='https://script.google.com/macros/s/AKfycbzK9xsCOuYT7bthNmqW58eK8SAOsyKHI9g1jyk2lU1_RL5F08My2KkMwr1KMNyPCxf_Zw/exec';
const style=document.createElement('style');
style.textContent=`#programs .accordions{grid-template-columns:repeat(4,minmax(0,1fr))!important}.sf-feedback{width:min(1180px,calc(100% - 40px));margin:10px auto 20px;border:1px solid #e4d8fa;border-radius:16px;background:linear-gradient(135deg,#f7f3ff,#fff8f3);overflow:hidden}.sf-feedback summary{list-style:none;cursor:pointer;padding:13px 16px;display:flex;justify-content:space-between;font-size:15px;font-weight:900;color:#5422a8}.sf-feedback summary::-webkit-details-marker{display:none}.sf-feedback summary::after{content:'▾';color:#7c3aed}.sf-feedback[open] summary::after{transform:rotate(180deg)}.sf-feedback-body{padding:0 16px 16px;max-width:780px}.sf-feedback p{margin:0 0 7px;color:#59657b;font-size:12px;line-height:1.5}.sf-feedback-form{display:grid;gap:10px;margin-top:12px}.sf-feedback-form label{display:grid;gap:5px;color:#344054;font-size:11px;font-weight:800}.sf-feedback-form select,.sf-feedback-form textarea{width:100%;border:1px solid #d9c9f3;border-radius:12px;background:#fff;color:#172033;font:500 13px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;padding:10px 12px}.sf-feedback-form textarea{min-height:104px;resize:vertical}.sf-feedback-consent{grid-template-columns:18px 1fr!important;align-items:start;font-weight:500!important;line-height:1.45}.sf-feedback-consent input{margin-top:2px}.sf-feedback-actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.sf-feedback button{border:0;border-radius:12px;padding:11px 15px;background:linear-gradient(135deg,#7540e8,#9a3fd0);color:#fff;font-weight:800;cursor:pointer}.sf-feedback button:disabled{opacity:.55}.sf-feedback-hint,.sf-feedback-status{font-size:10px;color:#7a8293}.sf-feedback-status{min-height:15px}.sf-feedback-status.error{color:#b42318}.sf-feedback-status.ok{color:#087a45}.sf-hp{position:absolute!important;left:-10000px!important;width:1px!important;height:1px!important;overflow:hidden!important}@media(max-width:900px){#programs .accordions{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:650px){#programs .accordions{grid-template-columns:1fr!important}.sf-feedback{width:calc(100% - 28px)}.sf-feedback-actions{display:grid}.sf-feedback button{width:100%}}`;
document.head.appendChild(style);
const footer=document.querySelector('.footer');if(!footer||document.querySelector('.sf-feedback'))return;
const box=document.createElement('details');box.className='sf-feedback';box.setAttribute('aria-label','Обратная связь');
box.innerHTML=`<summary>Обратная связь</summary><div class="sf-feedback-body"><p>Отзыв получит только владелец Step-Flow by SK AI Art — публично он не появится.</p><p><b>Не указывайте</b> имя, телефон, email, адрес, пароли, ключи, платёжные или другие личные данные.</p><form class="sf-feedback-form" novalidate><label>Тип отзыва<select name="type"><option>Ошибка на сайте</option><option>Предложение</option><option>Непонятный момент</option><option>Другое</option></select></label><label>Ваш отзыв<textarea name="message" maxlength="2000" placeholder="Опишите, что произошло или что можно улучшить" required></textarea></label><label class="sf-hp" aria-hidden="true">Сайт<input name="website" autocomplete="off" tabindex="-1"></label><label class="sf-feedback-consent"><input type="checkbox" name="consent" required><span>Я согласен на передачу и обработку отзыва через Google для улучшения сайта и прочитал раздел <a href="#privacy">«Конфиденциальность»</a>.</span></label><div class="sf-feedback-actions"><button type="submit">Отправить</button><span class="sf-feedback-hint">Хранение — до 90 дней</span></div><div class="sf-feedback-status" role="status" aria-live="polite"></div></form></div>`;
footer.parentNode.insertBefore(box,footer);
const form=box.querySelector('form'),message=form.elements.message,status=box.querySelector('.sf-feedback-status');
const clean=value=>{let s=String(value).replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim();if(/^[=+\-@]/.test(s))s="'"+s;return s};
form.addEventListener('submit',async e=>{e.preventDefault();status.className='sf-feedback-status';const text=clean(message.value);
 if(form.elements.website.value)return;
 if(text.length<5){status.textContent='Напишите хотя бы несколько слов.';status.classList.add('error');message.focus();return}
 if(!form.elements.consent.checked){status.textContent='Для отправки необходимо согласие на обработку отзыва.';status.classList.add('error');return}
 const last=Number(localStorage.getItem('sfFeedbackAt')||0);if(Date.now()-last<30000){status.textContent='Подождите 30 секунд перед повторной отправкой.';status.classList.add('error');return}
 const button=form.querySelector('button');button.disabled=true;button.textContent='Отправляем…';status.textContent='';
 try{await fetch(ENDPOINT,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({type:clean(form.elements.type.value),message:text,page:location.href.split('#')[0],website:''})});localStorage.setItem('sfFeedbackAt',String(Date.now()));form.reset();status.textContent='Спасибо! Отзыв отправлен владельцу.';status.classList.add('ok')}
 catch(err){status.textContent='Не удалось отправить. Проверьте интернет и попробуйте ещё раз.';status.classList.add('error')}
 finally{button.disabled=false;button.textContent='Отправить'}
});
})();
